class Config:
    video_path = "Your video path"
    description_file_path = "Your file descript path, txt btw"
    instagram_cookies_file = "instagram_cookies.pkl"
    tiktok_cookies_file = "tiktok_cookies.pkl"
    youtube_cookies_file = "youtube_cookies.pkl"
    snapchat_username = "ur snap username"
    snapchat_password = "ur snap password"
    instagram_username = "ur insta username"
    instagram_password = "ur insta username"
    tiktok_username = "ur tiktok username"
    tiktok_password = "ur tiktok username"
    youtube_email = "ur yt email"
    youtube_password = "ur yt username"
