class Config:
    video_path = "Your video path"
    description_file_path = "Your file descript path, txt btw"
    instagram_cookies_file = "instagram_cookies.pkl"
    tiktok_cookies_file = "tiktok_cookies.pkl"
    youtube_cookies_file = "youtube_cookies.pkl"
    snapchat_username = "ur_snap_username"
    snapchat_password = "ur_snap_password"
    instagram_username = "ur_insta_username"
    instagram_password = "ur_insta_username"
    tiktok_username = "ur_tiktok_username"
    tiktok_password = "ur_tiktok_username"
    youtube_email = "ur_yt_email"
    youtube_password = "ur_yt_username"
